---
- name: install apache & php & mysql
  hosts: fdr-prod
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Install apache2
      package: name=apache2
        state=present
    - name: "Install pip"
      package: name=python3-pip state=present
    - name: Install libmysqlclient-dev
      package: name=libmysqlclient-dev state=present
    - name: Install the Python MySQLB module
      pip: name=mysqlclient
    # - name: Install the Python MySQLB module
    #   pip: name=pymysql
    - name: Install apache2-php
      package:
        name: libapache2-mod-php
        state: present
    - name: Install php-cli
      package:
        name: php7.4-cli
        state: present
    - name: Install php-mcrypt
      package:
        name: mcrypt
        state: present
    - name: Install php-gd
      package:
        name: php7.4-gd
        state: present
    - name: Install php-mysql
      package:
        name: php-mysql
        state: present
    - name: Install mysql
      package:
        name: mysql-server
        state: present
    - name: Install npm
      package:
        name: npm
        state: present
    - name: add-apt-repository ppa:ondrej/php
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes
    - name: install bc-math
      package:
        name: php7.4-bcmath
        state: present
    - name: install curl
      package:
        name: php7.4-curl
        state: present
    - name: install  php7.4-redis
      package:
        name: php7.4-redis
        state: present
    - name: install redis-server
      package:
        name: redis-server
        state: present
    - name: restart redis service
      service:
        name: redis
        state: restarted
    - name: restart apache
      service:
        name: apache2
        state: restarted
