- name: create a remote backup
  mysql_db:
    name: foodreso_eav_dev
    state: dump
    target: /path/to/remote/backup/folder/dump.sql
    login_host: localhost
    login_user: mysql_dba
    login_password: enter_password_here
  tags:
    - db
    - backup

- name: Synchronize app directory
  synchronize:
    src: /path/to/control/backup/folder/
    dest: /path/to/remote/backup/folder/
    mode: pull
    use_ssh_args: yes
    rsync_opts:
      - "-azP"
  tags:
    - db
    - backup

# OR

- name: copy the database to the development server
  raw: rsync /path/to/backup/folder/dump.sql user@197.210.226.57:/home/user/code/foodres/storage/logs/
  ignore_errors: yes
  tags:
    - db
    - backup
