- name: Ensure mysql-server is installed latest version
  package:
    name: mysql-server
    state: latest
  tags: db,installation

- name: Installing python module MySQL-python
  pip:
    name: MySQL-python
  tags: db,setup


- name: Install libmysqlclient-dev
  package:
    name: libmysqlclient-dev
    state: present
    
- name: Install the Python MySQLB module
  pip:
    name: mysqlclient
    
- name: Install php-mysql
  package:
    name: php-mysql
    state: present
    
- name: Install php-mysql
  package:
    name: php-mysql
    state: present
    
- name: Ensure mysql-server is running
  service:
    name: mysql
    state: started